### ISSUE TITLE
Let Variables have a default value of star=False

### ISSUE THREAD

**Issue by djinnome** [y0-causal-inference/y0#103]
I originally suggested that Variables have a default value of `star=None`, because  I thought it would be simpler to implement, but it gets really confusing when `Y != ~~Y` because `Y.star==None` and `(~~Y).star == False`

Also, I thought we should allow `star=None` because the ID* algorithm infers the value from the parents in the counterfactual graph, but what I didn't realize is that if the inferred value is different from the specified value in gamma, then that just raises an INCONSISTENT error.

**Comment by djinnome** [comment]
Lastly, it seems that if I specify `~~Y` that turns it into an `Intervention` variable, so that `Y != ~~Y` for Type reasons, too.
I'm not sure if we really need `Intervention` variables anymore.  We just need `Variable` and `CounterfactualVariable`

**Comment by cthoyt** [comment]
Not sure what the current thought process is on this. Rather than changing the expressivity of the DSL, it would probably be better to start by writing more pre-conditions (and perhaps also post-conditions) for functions to make sure that the DSL elements passed have the correct properties

**Comment by djinnome** [comment]
I no longer think Variables should have a default value.
