### ISSUE TITLE
Counterfactual Transportability ID Algorithm

### ISSUE THREAD

**Issue by cthoyt** [y0-causal-inference/y0#123]
This is like ID* to general transportability (#122)

> Counterfactual Transportability: A Formal Approach
J. Correa, S. Lee, E. Bareinboim.
ICML-22. In Proceedings of the 39th International Conference on Machine Learning.
Columbia CausalAI Laboratory, Technical Report (R-82), May, 2022. [[pdf](https://causalai.net/r82.pdf), [bib](https://causalai.net/references/r82.bib)]

**Comment by djinnome** [comment]
The notebook should first include the examples from the paper, and then additional examples if needed.
