### ISSUE TITLE
Enable D-separation on counterfactual graphs

### ISSUE THREAD

**Issue by djinnome** [y0-causal-inference/y0#134]
It turns out we need to check for D-separation in the counterfactual graph in order to fix the flaw in the ID* algorithm. However, if we try to do so, we currently get this error when running 
[test_id_star.py](https://github.com/y0-causal-inference/y0/blob/17d79830975ff69236edf9c268e5a2df991b3ede/tests/test_algorithm/test_id_star.py#LL322C1-L344C133)

```python

test_id_star.py:344:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../src/y0/algorithm/identify/id_star.py:360: in simplify_counterfactual
    if are_d_separated(
../../src/y0/algorithm/conditional_independencies.py:165: in are_d_separated
    admg = graph.to_admg()
../../src/y0/graph.py:120: in to_admg
    self.raise_on_counterfactual()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ self = NxMixedGraph(directed=<networkx.classes.digraph.DiGraph object at 0x7f7839123df0>, undirected=<networkx.classes.graph.Graph object at 0x7f7839123e80>)
    def raise_on_counterfactual(self) -> None:
    """Raise an error if this is a counterfactual graph.
    :raises ValueError: if this graph is a counterfactual graph
    """
    if self.is_counterfactual():
>           raise ValueError("This operation is not available for counterfactual graphs")
E           ValueError: This operation is not available for counterfactual graphs
../../src/y0/graph.py:90: ValueError'


Edited<https://teams.microsoft.com/l/message/19:3efe1b0be7b14e718c36f5cfe71dd95c@thread.tacv2/1683000130755?tenantId=d6faa5f9-0ae2-4033-8c01-30048a38deeb&amp;groupId=940a4654-27a9-4a94-a146-e052b85ba421&amp;parentMessageId=1683000130755&amp;teamName=KESTREL&amp;channelName=Task 3&amp;createdTime=1683000130755&amp;allowXTenantAccess=false>
```

**Comment by cthoyt** [comment]
I think the question is do we need an alternate implementation for counterfactual graphs? Ot should the existing one work without modification?

**Comment by djinnome** [comment]
I don't see any reason why it wouldn't work, but maybe I should create some tests to confirm that.

**Comment by djinnome** [comment]
One potential issue is that the way `are_d_separated` currently works is to convert the NxMixedGraph to an Ananke ADMG. If it is a counterfactual, the intervention nodes are lost. Perhaps the right thing to do is convert the node to a string. That should work regardless of whether it is a Variable or CounterfactualVariable

https://github.com/y0-causal-inference/y0/blob/17d79830975ff69236edf9c268e5a2df991b3ede/src/y0/graph.py#L118-L127

**Comment by djinnome** [comment]
If we want to remove ADMG dependencies, we then just need to implement the following functions:

* `get_moral_links`
* `disorient`
*  `ancestors` (I think we have that one already)
