### ISSUE TITLE
Error in DSL.py in building Probability objects from strings applying conditional logic to sets 

### ISSUE THREAD

**Issue by rjc955** [y0-causal-inference/y0#209]
Typing `P({X}|{Y,Z})` should create a `Probability` object with the representation `P(X|Y,Z)`. Instead, it creates `P(X,Y,Z)`.

<img width="226" alt="Conditional_Probability_from_Sets_Issue" src="https://github.com/y0-causal-inference/y0/assets/76447201/b49c64a9-90f0-473d-8e63-b7cd94cafc86">

**Comment by cthoyt** [comment]
Nope, this is totally correct. You're using the bar operator between two sets, which takes the h ion of the sets. Then the union set XYZ is passed to the construction which makes a joint distributor over all of them

**Comment by rjc955** [comment]
Got it, thanks very much!
