### ISSUE TITLE
Unexplained behavior when instantiating a Population Probability

### ISSUE THREAD

**Issue by rjc955** [y0-causal-inference/y0#211]
The next two commented-out lines produce a mypy error:
```Python
pi1 = Population("pi1")
test_1_district_probability = PP[pi1](Z | X1)
```
Here's the error: 
```Python
error: Type application targets a non-generic function or class  [misc]
```
`test_transport.py` uses a similar syntax and does not trigger the error,
  so I'm probably missing something simple.

The next line does not trigger an error:
```Python
test_1_district_probability = PP[Population("pi1")](Z | X1)
```

**Comment by djinnome** [comment]
To be clear, this does not trigger an error in the python interpreter, only in mypy, which may suggest a bug in mypy?

**Comment by djinnome** [comment]
Now the problem is no longer being reported by mypy, so maybe the problem has been fixed?

**Comment by rjc955** [comment]
The issue reappeared and I found the [source](https://github.com/python/mypy/issues/7568) of the problem. Explicitly assigning a type to the alias `PP` when instantiating it at the end of `dsl.py` gets rid of the MyPy errors. It's fixed in [this](https://github.com/y0-causal-inference/y0/commit/2c837b73a090cf0058f9de25ba60470f77b5950c) commit, currently just in the `counterfactual_transportability` branch.
