### ISSUE TITLE
Update causaleffect DESCRIPTION file

### ISSUE THREAD

**Issue by hmhummel** [y0-causal-inference/y0#224]
In order to document causaleffect, we should add `Roxygen: list(markdown = TRUE)` to the DESCRIPTION file in the test-simplify branch in order to use roxygen2.

**Comment by djinnome** [comment]
You can create inline comments, such as `Roxygen: list(markdown=TRUE)`

or you can create block comments

```R
Roxygen: list(markdown = TRUE)
```

**Comment by djinnome** [comment]
- [ ] first item
- [ ] second todo item
- [ ] third todo item

**Comment by hmhummel** [comment]
Added `Roxygen: list(markdown = TRUE)` to the DESCRIPTION file
