### ISSUE TITLE
Create .Rd documentation for join.R

### ISSUE THREAD

**Issue by hmhummel** [y0-causal-inference/y0#226]
Create .Rd documentation for Tikka's `join` function using roxygen2 so that when `?join` is run, documentation will appear.

**Comment by cthoyt** [comment]
@hmhummel though on related topics to Y0, these issues appear to be irrelevant for this repository as they seem to be about R code. Please make sure you put them in the correct place

**Comment by hmhummel** [comment]
Hi @cthoyt thanks so much – will do! So sorry to have caused chaos; I am still getting familiar with Git :)
