### ISSUE TITLE
Interventions on the lhs of @

### ISSUE THREAD

**Issue by djinnome** [y0-causal-inference/y0#94]
In order to represent the value of a counterfactual variable (other than the one intervened on), we need to enable `~Y @ ~X`

This would enable the ability to represent counterfactual  probabilities such as:

- The probability of necessary causation:  `P(~y @ ~x | x, y)`
- The probability of sufficient causation:  `P(y @ x | ~x, ~y)`
- The probability of necessary and sufficient causation:  `P(y @ x, ~y @ ~x)`
- It would also enable events of probability 1:  `P(x @ x)` and `P(~x @ ~x)`
- It would also enable events of probability 0:  `P(x @ ~x)` and `P(~x @ x)`

**Comment by djinnome** [comment]
This does change the semantics a bit.  Previously, the `~` indicated a value different from what was observed.  Now  what is observed could be `~x`. . If we did not want to change the semantics, then there would be no way to distinguish probability of necessary causation from probability of sufficient causation.  Furthermore, it is not even possible to specify events of probability 0, because previously `P(X @ ~X)` meant the "Variable `X` is assigned a value different from its observed value), now it means "The probability that `X` attains value `x` when it is set to `~x`, which is 0 (unless `x == ~x`), which we disallow.

**Comment by cthoyt** [comment]
Interesting description! I think this is actionable but it would be good to have a chat on Monday first

**Comment by cthoyt** [comment]
Addressed in #98
